<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>ImperiumRDP.GUI</RootNamespace>
    <AssemblyName>ImperiumRDP</AssemblyName>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImperiumRDP.Agent\ImperiumRDP.Agent.csproj" />
    <ProjectReference Include="..\ImperiumRDP.Viewer\ImperiumRDP.Viewer.csproj" />
  </ItemGroup>

</Project>
