<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>ImperiumRDP.Agent</RootNamespace>
    <AssemblyName>ImperiumRDP.Agent</AssemblyName>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImperiumRDP.Shared\ImperiumRDP.Shared.csproj" />
  </ItemGroup>

</Project>
